In [1]:
# Employee management System

In [2]:
# database

In [3]:
# import mysql.connector
# conn=mysql.connector.connect(user='root',password='Python@123',
#                              host='localhost')

# qur='create database python_db'
# mycur=conn.cursor()
# mycur.execute(qur)
# mycur.close()
# conn.close()

In [4]:
# import mysql.connector
# conn=mysql.connector.connect(user='root',password='Python@123',
#                              host='localhost',database='python_db')

# qur='create table newemp(name VARCHAR(40),mobno VARCHAR(20),dept VARCHAR(40),salary VARCHAR(20))'
# mycur=conn.cursor()
# mycur.execute(qur)
# mycur.close()
# conn.close()

In [ ]:
import mysql.connector
import pymysql
from tkinter import *
from tkinter import messagebox
from tkinter import ttk
win=Tk()
win.title('EMPLOYEE MANAGEMENT SYSTEM')
win.config(bg='gray')
win.geometry('800x600')

def show():
    treev.delete(*treev.get_children())
    conn=pymysql.connect(user='root',password='Python@123',
                             host='localhost',database='python_db')
    qur='SELECT * FROM newemp'
    mycur=conn.cursor()
    mycur.execute(qur)
    tup1=mycur.fetchall()
    for i in tup1:
        treev.insert('',END,values=(i[0],i[1],i[2],i[3]))
    mycur.close()
    conn.close()
        
    


def add():
    name=n1.get()
    mobno=m1.get()
    dept=d1.get()
    salary=s1.get()
    if name=='' or mobno=='' or dept=='' or salary=='':
        messagebox.showinfo('info','its a compulsory')
    else:
        conn=pymysql.connect(user='root',password='Python@123',
                             host='localhost',database='python_db')

        qur=f'INSERT INTO newemp VALUES("{name}","{mobno}","{dept}","{salary}")'
        mycur=conn.cursor()
        mycur.execute(qur)
        conn.commit()
        mycur.close()
        conn.close()
        messagebox.showinfo('info','Data is added successfully')
        n1.set('')
        m1.set('')
        d1.set('')
        s1.set('')
        
    

def salary():
    root=Tk()
    root.title('Salary')
    root.configure(bg='gray')
    root.geometry('800x800')
    def fun():
        sal_data=e7.get()
        if sal_data=='':
            messagebox.showinfo('info','its a compulsory')
        else:
            conn=pymysql.connect(user='root',password='Python@123',
                                 host='localhost',database='python_db')
    
            qur=f'SELECT salary FROM newemp WHERE name="{sal_data}"'
            mycur=conn.cursor()
            mycur.execute(qur)
            tup1=mycur.fetchone()
            l8.config(text=sal_data+"'s "+' salary '+tup1[0]+' Rs')
            mycur.close()
            conn.close()
            
        
    l7=Label(root,text='ENTER NAME',bd=5,relief='ridge',width=20)
    l7.place(x=100,y=40)
    var3=StringVar()
    e7=Entry(root,textvariable=var3,width=40,bd=5,relief='ridge')
    e7.place(x=260,y=40)
    b9=Button(root,text='SHOW',width=20,command=fun)
    b9.place(x=260,y=80)
    l8=Label(root,text='Salary is here',height=4,width=25)
    l8.place(x=100,y=150)

    
    root.mainloop()

def delete():
    del_data=var1.get()
    if del_data=='':
        messagebox.showinfo('info','its a compulsory')
    else:
        conn=pymysql.connect(user='root',password='Python@123',
                             host='localhost',database='python_db')

        qur=f'DELETE FROM newemp WHERE name="{del_data}"'
        mycur=conn.cursor()
        mycur.execute(qur)
        conn.commit()
        mycur.close()
        conn.close()
        messagebox.showinfo('info','Data is deleted successfully')
        var1.set('')

def select():
    up_data=var2.get()
    if up_data=='':
        messagebox.showinfo('info','its a compulsory')
    else:
        conn=pymysql.connect(user='root',password='Python@123',
                             host='localhost',database='python_db')

        qur=f'SELECT * FROM newemp WHERE name="{up_data}"'
        mycur=conn.cursor()
        mycur.execute(qur)
        result=mycur.fetchone()
        e1.insert(0,result[0])
        e2.insert(0,result[1])
        e3.insert(0,result[2])
        e4.insert(0,result[3])
        mycur.close()
        conn.close()
    


def update():
    name=n1.get()
    mobno=m1.get()
    dept=d1.get()
    salary=s1.get()
    if name=='' or mobno=='' or dept=='' or salary=='':
        messagebox.showinfo('info','its a compulsory')
    else:
        conn=pymysql.connect(user='root',password='Python@123',
                             host='localhost',database='python_db')

        qur=f'UPDATE newemp SET mobno="{mobno}",dept="{dept}",salary="{salary}" WHERE name="{name}"'
        mycur=conn.cursor()
        mycur.execute(qur)
        conn.commit()
        mycur.close()
        conn.close()
        messagebox.showinfo('info','Data is updated successfully')
        n1.set('')
        m1.set('')
        d1.set('')
        s1.set('')
    
    
def clear():
    treev.delete(*treev.get_children())
    
# main label
l0=Label(win,text='EMPLOYEE MANAGEMENT SYSTEM',bg='white',fg='black',width=40,bd=5,
        relief='ridge',font=('times new roman',18,'bold'))
l0.place(x=268,y=40)

# # name label and entry

l1=Label(win,text='EMPLOYEE NAME',bg='white',fg='black',width=20,bd=5,
        relief='ridge',font=('times new roman',12,'bold'))
l1.place(x=190,y=100)


n1=StringVar()
e1=Entry(win,textvariable=n1,bd=5,relief='ridge',
         bg='white',fg='black',width=40,font=('times new roman',12,'bold'))

e1.place(x=390,y=100)

# #mob no label and entry
l2=Label(win,text='MOBILE NUMBER',bg='white',fg='black',width=20,bd=5,
        relief='ridge',font=('times new roman',12,'bold'))
l2.place(x=190,y=140)


m1=StringVar()
e2=Entry(win,textvariable=m1,bd=5,relief='ridge',
         bg='white',fg='black',width=40,font=('times new roman',12,'bold'))

e2.place(x=390,y=140)

# dept label and entry

l3=Label(win,text='DEPARTMENT',bg='white',fg='black',width=20,bd=5,
        relief='ridge',font=('times new roman',12,'bold'))
l3.place(x=190,y=180)


d1=StringVar()
e3=Entry(win,textvariable=d1,bd=5,relief='ridge',
         bg='white',fg='black',width=40,font=('times new roman',12,'bold'))

e3.place(x=390,y=180)

# salary label and entry

l4=Label(win,text='SALARY',bg='white',fg='black',width=20,bd=5,
        relief='ridge',font=('times new roman',12,'bold'))
l4.place(x=190,y=220)


s1=StringVar()
e4=Entry(win,textvariable=s1,bd=5,relief='ridge',
         bg='white',fg='black',width=40,font=('times new roman',12,'bold'))

e4.place(x=390,y=220)

#buttons ADD,SHOW,SALARY,EXIT

b1=Button(win,text='SHOW',width=12,command=show,bd=5,relief='ridge',
          bg='black',fg='white',font=('times new roman',11,'bold'))
b1.place(x=280,y=300)

b2=Button(win,text='ADD',width=12,command=add,bd=5,relief='ridge',
          bg='black',fg='white',font=('times new roman',11,'bold'))
b2.place(x=510,y=300)

b3=Button(win,text='EXIT',width=12,command=win.destroy,bd=5,relief='ridge',
          bg='black',fg='white',font=('times new roman',11,'bold'))
b3.place(x=280,y=340)

b4=Button(win,text='SALARY',width=12,command=salary,bd=5,relief='ridge',
          bg='black',fg='white',font=('times new roman',11,'bold'))
b4.place(x=510,y=340)


# delete logic
# label entry button

l5=Label(win,text='ENTER THE NAME>>',bg='white',fg='black',width=20,bd=5,
        relief='ridge',font=('times new roman',12,'bold'))
l5.place(x=190,y=400)


var1=StringVar()
e5=Entry(win,textvariable=var1,bd=5,relief='ridge',
         bg='white',fg='black',width=40,font=('times new roman',12,'bold'))

e5.place(x=390,y=400)

b5=Button(win,text='DELETE',width=12,command=delete,bd=5,relief='ridge',
          bg='black',fg='white',font=('times new roman',11,'bold'))
b5.place(x=390,y=440)

# update label ,entry ,2 buttons

l6=Label(win,text='ENTER THE NAME>>',bg='white',fg='black',width=20,bd=5,
        relief='ridge',font=('times new roman',12,'bold'))
l6.place(x=190,y=490)


var2=StringVar()
e6=Entry(win,textvariable=var2,bd=5,relief='ridge',
         bg='white',fg='black',width=40,font=('times new roman',12,'bold'))

e6.place(x=390,y=490)

b6=Button(win,text='SELECT',width=12,command=select,bd=5,relief='ridge',
          bg='black',fg='white',font=('times new roman',11,'bold'))
b6.place(x=280,y=540)

b7=Button(win,text='UPDATE',width=12,command=update,bd=5,relief='ridge',
          bg='black',fg='white',font=('times new roman',11,'bold'))
b7.place(x=450,y=540)

#   treevview

treev=ttk.Treeview(win,height=23)
treev.place(x=760,y=100,width=510)

treev["columns"] = ("1", "2", "3","4")
treev['show'] = 'headings'

treev.column("1", width = 90, anchor ='c')
treev.column("2", width = 90, anchor ='se')
treev.column("3", width = 90, anchor ='se')
treev.column("4", width = 90, anchor ='se')


treev.heading("1", text ="Emp_Name")
treev.heading("2", text ="Mobile No")
treev.heading("3", text ="Dept")
treev.heading("4", text ="Salary")

# clear button

b8=Button(win,text='CLEAR',width=12,command=clear,bd=5,relief='ridge',
          bg='black',fg='white',font=('times new roman',11,'bold'))
b8.place(x=970,y=590)


win.mainloop()

In [ ]:
# mock >>>

In [ ]:
# project-resume 
# python
# stats 

# sql excel powebi

In [ ]:
# mock >>